services:
  api:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    env_file:
      - ./backend/.env
    depends_on:
      - db
    networks:
      - backend

  db:
    container_name: db
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=taskmanager
      - POSTGRES_PASSWORD=Task@Manager
      - POSTGRES_DB=taskmanager
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - api
    networks:
      - frontend

volumes:
  db-data: {}

networks:
  backend:
  frontend:
